### PR TITLE
Add github action to lint and check code formatting

### PR DESCRIPTION
**Pull request by benjamb**
Makes use of pre-commit to run `black` and `flake8` against the code base.

Adds a brief bit of documentation to `CONTRIBUTING.md` on setting up the hooks in your local repository.

### CODE REVIEW

**Comment by wolfv** [comment]
ah! cool!

I have some changes to the Python ... should we merge them before?

**Comment by wolfv** [comment]
I'll rebase my changes.

**Comment by benjamb** [comment]
@wolfv I likely would have been fine to rebase on top of your branch, hopefully it's not too much of a pain for you. Thanks a lot!

**Comment by wolfv** [comment]
already done! :)

**Pull request merged**
