### PR TITLE
Fix Readme tutorial

### PR DESCRIPTION
**Pull request by adriendelsalle**
Description
--

The current tutorial in Readme is broken

``` bash
$ uvicorn quetz.main:app --reload
...
RuntimeError: Directory 'channels' does not exist
```

``` bash
$ ./test-cli-client.sh
./test-cli-client.sh: 2: ./test-cli-client.sh: curl: not found
```

Proposition
--
Add curl dependency 
Create channels directory

### CODE REVIEW

**Comment by benjamb** [comment]
The `test-cli-client.sh` script is ultimately obsolete now there is the quetz-client tool, so it might make more sense to simply remove that rather than pull in curl for it.

It also might be worth creating the channel directory during app startup (prior to mounting in `main.py`), rather than an explicit step for the user.

**Comment by adriendelsalle** [comment]
Hi @benjamb !

Thanks for your comment, I modified the proc to:
- install `quetz-client` instead of `curl`
- use `quetz-client` to push packages (requires the API token stored in a env variable for now)

The package repository bootstrap could be done by a single command. Maybe I missed it, I will open a dedicated issue otherwise.
Is it OK for you that way?
Thanks!

**Comment by wolfv** [comment]
looks good to me!

**Comment by wolfv** [comment]
thanks for the contribution

**Pull request merged**
